IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CURRENT_STATS]') AND TYPE IN (N'U'))
CREATE TABLE  CURRENT_STATS (
  TIME_STAMP DATE NOT NULL,
  NODE_ID VARCHAR (40) NOT NULL,
  TRANSACTION_COUNT INT NOT NULL,
  TRANSACTION_COUNT_ENCRYPTED VARCHAR(400) NOT NULL
);
