/*
 * Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

package org.wso2.carbon.inbound.endpoint.protocol.grpc.util;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventservice.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payload = 1;</code>
   */
  String getPayload();
  /**
   * <code>string payload = 1;</code>
   */
  com.google.protobuf.ByteString
      getPayloadBytes();

  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */
  int getHeadersCount();
  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */
  boolean containsHeaders(
          String key);
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getHeaders();
  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */
  java.util.Map<String, String>
  getHeadersMap();
  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */

  String getHeadersOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */

  String getHeadersOrThrow(
          String key);
}
