// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

package org.wso2.micro.integrator.inbound.endpoint.protocol.grpc.util;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventservice.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payload = 1;</code>
   */
  String getPayload();
  /**
   * <code>string payload = 1;</code>
   */
  com.google.protobuf.ByteString
      getPayloadBytes();

  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */
  int getHeadersCount();
  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */
  boolean containsHeaders(
          String key);
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getHeaders();
  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */
  java.util.Map<String, String>
  getHeadersMap();
  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */

  String getHeadersOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; headers = 2;</code>
   */

  String getHeadersOrThrow(
          String key);
}
